{
 "title": "OtusDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{status=\"200\"}[1m]))",
     "legendFormat": "Successful RPS"
    },
    {
     "expr": "sum (rate(http_server_requests_seconds_count{status=\"500\"}[1m]))",
     "legendFormat": "Error RPS"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{uri=\"/api/a\"}[1m]))",
     "legendFormat": "Fast endpoint 200...400 ms (/api/a)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/b\"}[1m]))",
     "legendFormat": "Slow endpoint 200...400 ms (/api/b)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/error-code\"}[1m]))",
     "legendFormat": "Endpoint with errors"
    },
    {
     "expr": "sum (rate(http_server_requests_seconds_sum[1m]))/sum (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Latency Quantile of Slow endpoint 200...400 ms (/api/b)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds{uri=\"/api/b\", quantile=\"0.5\"}",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": "http_server_requests_seconds{uri=\"/api/b\", quantile=\"0.95\"}",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": "http_server_requests_seconds{uri=\"/api/b\", quantile=\"0.99\"}",
     "legendFormat": "Quantile 0.99"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_sum[1m]))/sum (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "Average latency"
    }
   ]
  },
  {
   "title": "Latency Quantile of Fast endpoint 0...300 ms (/api/a)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds{uri=\"/api/a\", quantile=\"0.5\"}",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": "http_server_requests_seconds{uri=\"/api/a\", quantile=\"0.95\"}",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": "http_server_requests_seconds{uri=\"/api/a\", quantile=\"0.99\"}",
     "legendFormat": "Quantile 0.99"
    }
   ]
  }
 ]
}